# -*- coding: utf-8 -*-
"""denki_juyo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Lrboj5hBVZZ6JxJnfJ6t5xHqycOegv1U

# 神戸の電気使用量を予測する

AIリテラシー課題第一回で使用した時系列分析を、今回は神戸の電気使用量を予測するために使ってみる。

つもりでした。データ整形で詰まってます。
"""

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
import statsmodels.api as sm
import pandas as pd
import numpy as np
import requests
import io
from matplotlib import pylab as plt
# %matplotlib inline
from matplotlib.pylab import rcParams
rcParams['figure.figsize'] = 15, 6

kion_2020_data = np.loadtxt('/content/drive/My Drive/kion_2020.csv')
kion_2019_data = np.loadtxt('/content/drive/My Drive/kion_2019.csv')
denki_2020_data = np.loadtxt('/content/drive/My Drive/output_denki_2020.csv')
denki_2019_data = np.loadtxt('/content/drive/My Drive/output_denki_2019.csv')